services:
  prometheus:
    image: prom/prometheus
    volumes:
      - "./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"

    ports:
      - 9090:9090
    network_mode: host
  grafana:
    image: grafana/grafana
    volumes:
      - "./docker/grafana/datasources:/etc/grafana/provisioning/datasources"
      - "./docker/grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/main.yaml"
      - "./docker/grafana/dashboards:/var/lib/grafana/dashboards"
    ports:
      - 3000:3000
    network_mode: host
  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - "./docker/promtail/config.yml:/etc/promtail/config.yml"
      - "./log:/var/log"
      - "~/docker/go_auth/promtail:/usr/data/promtail"
    command: -config.file=/etc/promtail/config.yml

