services:
  prometheus:
    image: prom/prometheus
    volumes:
      - "./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"

    network_mode: host

  grafana:
    image: grafana/grafana
    volumes:
      - "./docker/grafana/datasources:/etc/grafana/provisioning/datasources"
      - "./docker/grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/main.yaml"
      - "./docker/grafana/dashboards:/var/lib/grafana/dashboards"
    ports:
      - "3000:3000"
    network_mode: host

  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    build:
      context: ./
      dockerfile: ./docker/promtail/Dockerfile

    volumes:
      - "./docker/promtail/config.yml:/etc/promtail/config.yml"
      - "./log:/var/log/auth"
      - "~/docker/go_auth/promtail:/usr/data/promtail"
    command: -config.file=/etc/promtail/config.yml

  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: auth
      PGDATA: /var/lib/postgresql/data/pgdata

    volumes:
      - "~/.docker_mounts/auth:/var/lib/postgresql/data"
