auth:
  salt: "nkE43783NOhVnp5MBpZ-"
  secret: "lk$98j(mncx725109jcoin&"
server:
  service: go_auth
  port: 3080
database:
  hostname: 127.0.0.1
  port : 5432
  username: user
  password: pass
  database: auth
  migrations: file://./migrations/db
