{
 "title": "Service Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(http_request_duration_seconds_bucket,instance)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(http_request_duration_seconds_bucket,service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Processor Stats",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(cpuinfo_sys_cores_total{instance=\"$instance\"})",
     "legendFormat": "Core Count"
    },
    {
     "expr": "avg(cpuinfo_sys_thread_total{instance=\"$instance\"})",
     "legendFormat": "Thread Count"
    },
    {
     "expr": "avg(go_memstats_sys_bytes{instance=\"$instance\"})",
     "legendFormat": "Application Memory"
    },
    {
     "expr": "avg(memstats_sys_available_bytes{instance=\"$instance\"})",
     "legendFormat": "Total Memory"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 10, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"system\",service=\"$service\"}",
     "maxLines": 1000
    }
   ]
  },
  {
   "title": "Status Codes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(increase(http_request_duration_seconds_count{instance=\"$instance\", code!~\"3..\"}[$__range])) by (code)"
    }
   ]
  },
  {
   "title": "Processor Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{instance=\"$instance\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{instance=\"$instance\", code=~\"2..\"}[30s])) by (instance, method, handler) / sum(increase(http_request_duration_seconds_count{instance=\"$instance\", code=~\"...\"}[30s])) by (instance, method, handler)",
     "legendFormat": "{{handler}} {{method}}"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "avg(rate(http_request_duration_seconds_count{instance=\"$instance\"}[$__rate_interval])) by (method, handler, code)",
     "legendFormat": "{{handler}} {{method}} [{{code}}]"
    }
   ]
  },
  {
   "title": "Http Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{instance=\"$instance\"}[$__rate_interval])) by (handler, method, code)",
     "legendFormat": "{{handler}} {{method}} [{{code}}]"
    }
   ]
  }
 ]
}