server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /usr/data/promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: system
      service: go_auth
      __path__: /var/log/*log
  pipeline_stages:
  - match:
      selector: '{userService="go_auth"}'
      stages:
      - regex:
          expression: 'time=(?P<time>[^\s]+).*level=(?P<level>[^\s]+).*source=(?P<source>.*).*msg=\"(?P<msg>.*)\".*userService=(?P<userService>.*)'
      - timestamp:
          source: time
          format: 2024-04-05T22:43:56.511-04:00
      - labels:
          level:
          source:
      - output:
          source: msg

